version: '3.8'

services:
  tomcat:
    image: tomcat:latest
    ports:
      - "9090:8080"  # Change 9090 to any port you prefer
    volumes:
      - type: bind
        source: ./webapp
        target: /usr/local/tomcat/webapps/ROOT